exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "vendor", "Gemfile", "Gemfile.lock", "Guardfile", "assets.yml"]
highlighter: pygments

gems: [jekyll-sitemap, octopress-autoprefixer]

sass:
  style: :compressed
  sass_dir: assets/stylesheets

title: Dr. Bill Moore - Positive, Focused and Fighting
description: I am a performance psychology consultant working with business professionals helping both individuals and groups perform at optimal levels when it counts.
url: http://www.drbillmoore.com
permalink: pretty
production_url: http://www.drbillmoore.com
contact_email: bill@mooreperform.com

google_analytics: "UA-62087264-1"
google_site_verification: "XIRPLBecm0oPqdOcnXBReTekVqM_n25ZcSr6elVdHCw"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]

collections:
  seminars:
    output: true
  books:
    output: true
